[logging]
level = "INFO"
config_path = "{{ cookiecutter.state_path }}/prefect/logging.yml"
log_prints = true


[server.database]
connection_url = "sqlite+aiosqlite:///{{ cookiecutter.state_path }}/prefect/prefect.db"
echo = false
migrate_on_start = true
# password = 'None'