# files who describe schema of data

datamodel:
  tables:
    - name: raw
      description: "Table containing the raw data"
      columns:
        - name: id
          type: string
          link: "id"
          description: "Unique identifier for each record"
        - name: launch_date
          type: datetime
          link: "net"
          description: "Date of the launch"
        - name: name
          type: string
          link: "name"
          description: "Name of the entity"
        - name: status
          type: string
          link: "status.abbrev"
          description: "Status of the launch"
        - name: launch_service_provider
          type: string
          link: "launch_service_provider.name"
          description: "Provider of the launch service"
        - name: launch_site
          type: string
          link: "pad.name"
          description: "Site of the launch"
        - name: country
          type: string
          link: "pad.country.name"
          description: "Country of the launch"
        - name: rocket
          type: string
          link: "rocket.configuration.name"
          description: "Name of the launcher"
        - name: mission
          type: string
          link: "mission.name"
          description: "Name of the mission"
        - name: mission_type
          type: string
          link: "mission.type"
          description: "Type of the mission"
    - name: processed
      description: "Table containing the processed data"
      columns:
        - name: country
          type: string
          description: "Country of the launch"
        - name: nb_launches
          type: integer
          description: "Number of launches"
        - name: nb_sucess
          type: integer
          description: "Number of successful launches"
